Repository Cosmic-Overlord/TerraGov-Marine-Corps, pull requests merged in 2023-01, with the labels that each got.

#3 Фикс зума с вайдскрином
  code/datums/view.dm
  code/game/objects/items.dm
  code/game/objects/items/binoculars.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/specialist.dm
  config/config.txt
Labels: good first issue

#7 Тот же фильтр у равы, чистая история комитов. Удар.
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: enhancement

#9 Добавление разрешений вайдскрина и фикс тада
  code/__DEFINES/preferences.dm
  code/controllers/configuration/entries/general.dm
  code/datums/view.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/login.dm
  code/modules/shuttle/mini_dropship.dm
  code/modules/shuttle/navigation_computer.dm
  config/config.txt
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Labels: enhancement

#12 Доработка вайдскрина
  code/modules/client/client_procs.dm
Labels: fix

#11 Переделал дефайны вайдскрина
  code/__DEFINES/preferences.dm
  code/controllers/configuration/entries/general.dm
  code/datums/view.dm
Labels: fix

#10 Улучшение дропподов
  code/game/objects/structures/droppod.dm
  tgui/packages/tgui/interfaces/Droppod.tsx
Labels: enhancement

#17 ob beacon for jaeger fc bundle
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: fix

#4 Crusher stomp fix
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
Labels: fix, balance

#19 Фикс отбрасывания
  code/controllers/subsystem/explosions.dm
  code/game/atoms_movable.dm
Labels: fix

#24 Добавление камеры дропподу
  code/game/objects/machinery/computer/camera_advanced.dm
  code/game/objects/structures/droppod.dm
  tgui/packages/tgui/interfaces/Droppod.tsx
Labels: enhancement

#18 Playable Facehuggers
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mode.dm
  code/_globalvars/lists/flavor_misc.dm
  code/_globalvars/lists/mobs.dm
  code/_onclick/xeno.dm
  code/game/objects/machinery/doors/airlock.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/facehugger/abilities_facehugger.dm
  code/modules/mob/living/carbon/xenomorph/castes/facehugger/castedatum_facehugger.dm
  code/modules/mob/living/carbon/xenomorph/castes/facehugger/facehugger.dm
  code/modules/mob/living/carbon/xenomorph/egg.dm
  code/modules/mob/living/carbon/xenomorph/embryo.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/xenomorph/xeno_structures.dm
  icons/UI_Icons/map_blips.dmi
  icons/Xeno/facehugger_playable.dmi
  tgmc.dme
Labels: enhancement, good first issue, help wanted

#14 Фикс джаггла
  code/modules/mob/living/living_defines.dm
  code/modules/projectiles/gun_system.dm
Labels: question, fix

#6 Hunter apha stealth increase
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Labels: balance
